name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-tests-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn lint
